
version: '3'
services:
  elasticsearch:
    image: elasticsearch:8.12.2
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
      - 1024:1024
    environment:
      - discovery.type=single-node
      - xpack.security.enabled= true
      - ELASTIC_PASSWORD=12345
      - ELASTICSEARCH_USERNAME=elastic
      - xpack.security.transport.ssl.enabled=false
      - xpack.security.http.ssl.enabled=false
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    mem_limit: 2048m

  redis:
    image: redis
    volumes:
      - ./data:/data
    ports:
      - 6379:6379

  movie_finder:
    image: movie_finder
    ports:
      - 5000:5000

volumes:
  esdata01:
    driver: local 